language: node_js
addons:
  apt:
    sources:
      - mono
    packages:
      - wine
      - fakeroot
      - dpkg
      - rpm
      - mono-complete
before_install:
  - npm install -g electron-forge
before_script:
  - npm run sass-compile
jobs:
  include:
    - stage: make
      script: electron-forge publish --platform=linux --target=s3
    - script: travis_wait electron-forge publish --platform=win32 --target=s3
    - script: electron-forge publish --platform=darwin --target=s3
