language: node_js
addons:
  apt:
    packages:
      - fakeroot
      - dpkg
      - rpm
before_install:
  - if [ $TRAVIS_OS_NAME = "osx" ]; then brew update && ln -s /usr/local/opt/openssl/include/openssl /usr/local/include; fi
  - npm install -g electron-forge
before_script:
  - npm run sass-compile
stages:
  - name: test
    if: type = pull_request
  - name: deploy
    if: type = push AND branch = master
jobs:
  include:
    - stage: test
      script: electron-forge package
      os: linux
    - script: electron-forge package
      os: osx
    - stage: deploy
      script: electron-forge publish
      os: linux
    - script: electron-forge publish
      os: osx
