language: node_js
mono: latest
addons:
  artifaces:
    region: ap-southeast-2
    working_dir: out
  apt:
    packages:
      - wine
      - fakeroot
      - dpkg
      - rpm
before_install:
  - npm install -g electron-forge
before_script:
  - npm run sass-compile
jobs:
  include:
    - stage: make
      script: electron-forge make --platform=linux
    - script: electron-forge make --platform=win32
    - script: electron-forge make --platform=darwin
