language: node_js
addons:
  apt:
    packages:
      - fakeroot
      - dpkg
      - rpm
before_install:
  - if [ $TRAVIS_OS_NAME = "osx" ]; then brew update && ln -s /usr/local/opt/openssl/include/openssl /usr/local/include; fi
stages:
  - name: test
    if: type = pull_request
  - name: deploy
    if: tag is present
jobs:
  include:
    - stage: test
      os: linux
    - os: osx
    - stage: deploy
      script: npm run deploy
      os: linux
    - script: npm run deploy
      os: osx
