language: node_js
addons:
  apt:
    packages:
      - wine
      - fakeroot
      - dpkg
      - rpm
      - mono
before_install:
  - npm install -g electron-forge
before_script:
  - npm run sass-compile
jobs:
  include:
    - stage: test
      script: electron-forge package --platform=linux
    - script: electron-forge package --platform=win32
    - stage: publish
      script: electron-forge publish --platform=win32 --arch=x64
    - script: electron-forge publish --platform=linux --arch=x64
