language: node_js
addons:
  apt:
    sources:
      - sourceline: 'deb http://download.mono-project.com/repo/ubuntu stable-xenial main'
    packages:
      - wine
      - fakeroot
      - dpkg
      - rpm
      - mono-complete
before_install:
  - npm install -g electron-forge
before_script:
  - npm run sass-compile
jobs:
  include:
    - stage: test
      script: electron-forge package --platform=linux
    - script: electron-forge package --platform=win32
    - stage: publish
      script: electron-forge publish --platform=win32 --arch=x64
    - script: electron-forge publish --platform=linux --arch=x64
