language: node_js
addons:
  apt:
    packages:
      - fakeroot
      - dpkg
      - rpm
before_install:
  - npm install -g electron-forge
before_script:
  - npm run sass-compile
jobs:
  include:
    - stage: make
      script: electron-forge publish --target=s3
      os:
        - linux
        - osx
