language: node_js
matrix:
  include:
    - os: linux
    - os: osx
addons:
  apt:
    packages:
      - fakeroot
      - dpkg
      - rpm
before_install:
  - if [ $TRAVIS_OS_NAME = "osx" ]; then brew update && ln -s /usr/local/opt/openssl/include/openssl /usr/local/include; fi
  - npm install -g electron-forge
before_script:
  - npm run sass-compile
jobs:
  include:
    - stage: deploy
    - script: electron-forge publish
      if: branch = master AND type = push
    - stage: test
    - script: electron-forge package
      if: type = pull_request
