language: node_js
os:
  - linux
  - osx
addons:
  apt:
    packages:
      - fakeroot
      - dpkg
      - rpm
before_install:
  - if [ $TRAVIS_OS_NAME = "osx" ]; then brew update && ln -s /usr/local/opt/openssl/include/openssl /usr/local/include; fi
  - npm install -g electron-forge
before_script:
  - npm run sass-compile
script:
  - electron-forge publish
