language: node_js
addons:
  apt:
    packages:
      - wine
      - fakeroot
      - dpkg
      - rpm
before_install:
  - npm install -g electron-forge
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
  - echo "deb http://download.mono-project.com/repo/ubuntu stable-xenial main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
  - sudo apt-get update
  - sudo apt install mono-complete
before_script:
  - npm run sass-compile
jobs:
  include:
    - stage: test
      script: electron-forge package --platform=linux
    - script: electron-forge package --platform=win32
    - stage: publish
      script: electron-forge publish --platform=win32 --arch=x64
    - script: electron-forge publish --platform=linux --arch=x64
