language: node_js
addons:
  apt:
    packages:
      - fakeroot
      - dpkg
      - rpm
before_install:
  - if [ $TRAVIS_OS_NAME = "osx" ]; then brew update && ln -s /usr/local/opt/openssl/include/openssl /usr/local/include; fi
jobs:
  include:
    - stage: test
    - stage: deploy electron
      script: npm run deploy:electron
      if: tag is present and tag =~ ^((?!beta).)*$
      os: linux
    - script: npm run deploy:electron
      if: tag is present and tag =~ ^((?!beta).)*$
      os: osx
    - stage: build and deploy
      env: BUCKET=integration.kinesiswebwallet.com TRAVIS_TAG=true
      if: branch = master and type = push
      script: npm run build:web
      deploy: &deploy
        provider: s3
        region: ap-southeast-2
        skip_cleanup: true
        bucket: $BUCKET
        local_dir: dist
        on:
          tags: true
    - env: BUCKET=uat.kinesiswebwallet.com
      if: tag is present
      script: npm run build:web
      deploy:
        <<: *deploy
    - env: BUCKET=www.kinesiswebwallet.com
      if: tag is present and tag =~ ^((?!beta).)*$
      script: npm run build:web
      deploy:
        <<: *deploy

