language: node_js
os:
  - linux
  - osx
addons:
  apt:
    packages:
      - fakeroot
      - dpkg
      - rpm
before_install:
  - npm install -g electron-forge
before_script:
  - npm run sass-compile
script:
  - electron-forge publish
