image: Visual Studio 2017
platform: x64
environment:
  nodejs_version: 8
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g electron-forge
  - npm install
before_build:
  - npm run sass-compile
for:
-
  branches:
    only:
      - master
  build_script:
    - electron-forge publish
-
  branches:
    except:
      - master
  build_script:
    - electron-forge package
