image: Visual Studio 2017
platform: x64
environment:
  nodejs_version: 8
  signtool: C:\Program Files (x86)\Windows Kits\10\bin\x86\signtool.exe
  outfile: C:\projects\wallet-desktop\out\make\squirrel.windows\x64\kinesis-wallet-setup.exe
branches:
  only:
    - master
cache:
  - '%APPDATA%\npm-cache'
  - node_modules
skip_non_tags: true
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
build_script:
  - ps: ./appveyor.ps1
