image: Visual Studio 2017
platform: x64
environment:
  nodejs_version: 8
branches:
  only:
    - master
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
build_script:
  - ps: powershell ./appveyor.ps1
