image: Visual Studio 2017
platform: x64
environment:
  nodejs_version: 8
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
skip_branch_with_pr: true
build_script:
  - if "%APPVEYOR_PULL_REQUEST_NUMBER%"=="" (npm run deploy) else (npm test)
