image: Visual Studio 2017
platform: x64
environment:
  nodejs_version: 8
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g electron-forge
  - npm install
before_build:
  - npm run sass-compile
skip_branch_with_pr: true
build_script:
  - ps: if (!$env:APPVEYOR_PULL_REQUEST_NUMBER) { electron-forge publish }
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER) { electron-forge package }
