image: Visual Studio 2017
platform: x64
environment:
  nodejs_version: 8
branches:
  only:
    - master
cache:
  - '%APPDATA%\npm-cache'
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g npm --quiet
  - npm ci --quiet
build_script:
  - ps: ./appveyor.ps1
